# Generated by Django 4.2.4 on 2023-12-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticker', models.TextField()),
                ('shares', models.IntegerField()),
                ('priceWhenBought', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.EmailField(max_length=254)),
            ],
        ),
    ]
